name: grakn
description: A Grakn REST API connector for the Grakn hyper-relational graph database.
version: 1.1.1
homepage: https://github.com/Tomen/grakn-dart
author: Tommi Enenkel <tommi.enenkel@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  logging: ^0.11.3+1

dev_dependencies:
  test: ^0.12.0
